import { createContext, useContext, useState, useEffect } from 'react';
import type { ReactNode } from 'react';
import type { OptimizationRecommendation, SourceMode, OptimizationAction, WorkflowStatus } from '../types';
import { recommendationsData as initialMockData } from './mockFactory';

interface DataContextType {
  sourceMode: SourceMode;
  setSourceMode: (mode: SourceMode) => void;
  activeData: OptimizationRecommendation[];
  csvData: OptimizationRecommendation[];
  uploadCsvData: (data: OptimizationRecommendation[]) => void;
  clearCsvData: () => void;
  dataFreshness: Date;
  csvMetrics: {
    totalRows: number;
    ownerCoverage: number;
    platforms: string[];
    dataQuality: 'Good' | 'Partial' | 'Poor';
  } | null;
  workflowActions: OptimizationAction[];
  createAction: (recommendation: OptimizationRecommendation) => void;
  updateActionStatus: (actionId: string, status: WorkflowStatus, payload?: Partial<OptimizationAction>) => void;
  resetWorkflow: () => void;
}

const DataContext = createContext<DataContextType | undefined>(undefined);

export const DataProvider = ({ children }: { children: ReactNode }) => {
  const [sourceMode, setSourceMode] = useState<SourceMode>('Mock Data');
  const [csvData, setCsvData] = useState<OptimizationRecommendation[]>([]);
  const [dataFreshness, setDataFreshness] = useState<Date>(new Date());
  const [workflowActions, setWorkflowActions] = useState<OptimizationAction[]>([]);

  // Load from local storage on mount
  useEffect(() => {
    try {
      const stored = localStorage.getItem('finops_imported_data');
      if (stored) {
        const parsed = JSON.parse(stored);
        if (Array.isArray(parsed) && parsed.length > 0) {
          // eslint-disable-next-line
          setCsvData(parsed);
          const savedMode = localStorage.getItem('finops_source_mode') as SourceMode;
           
          if (savedMode) setSourceMode(savedMode);
        }
      }

      const storedWorkflow = localStorage.getItem('finops_workflow_actions');
      if (storedWorkflow) {
        setWorkflowActions(JSON.parse(storedWorkflow));
      }
    } catch (e) {
      console.error('Failed to load data from local storage', e);
    }
  }, []);

  // Save to local storage on change
  useEffect(() => {
    if (csvData.length > 0) {
      localStorage.setItem('finops_imported_data', JSON.stringify(csvData));
    } else {
      localStorage.removeItem('finops_imported_data');
    }
    localStorage.setItem('finops_source_mode', sourceMode);
    localStorage.setItem('finops_workflow_actions', JSON.stringify(workflowActions));
    // eslint-disable-next-line
    setDataFreshness(new Date());
  }, [csvData, sourceMode, workflowActions]);

  const uploadCsvData = (data: OptimizationRecommendation[]) => {
    // If we already have data, we might want to append or merge, but for this version
    // we will simply append new data to existing CSV data.
    setCsvData(prev => [...prev, ...data]);
    setSourceMode('Imported CSV Data');
  };

  const clearCsvData = () => {
    setCsvData([]);
    setSourceMode('Mock Data');
  };

  const getActiveData = (): OptimizationRecommendation[] => {
    if (sourceMode === 'Mock Data') return initialMockData;
    if (sourceMode === 'Imported CSV Data') return csvData;
    // Hybrid Mode
    return [...initialMockData, ...csvData];
  };

  const activeData = getActiveData();

  const calculateDataQuality = (coverage: number): 'Good' | 'Partial' | 'Poor' => {
    if (coverage >= 80) return 'Good';
    if (coverage >= 40) return 'Partial';
    return 'Poor';
  };

  const csvMetrics = csvData.length > 0 ? {
    totalRows: csvData.length,
    ownerCoverage: Math.round((csvData.filter(d => !!d.owner).length / csvData.length) * 100),
    platforms: Array.from(new Set(csvData.map(d => d.platform))),
    dataQuality: calculateDataQuality(Math.round((csvData.filter(d => !!d.owner).length / csvData.length) * 100))
  } : null;

  const createAction = (rec: OptimizationRecommendation) => {
    // Generate basic action mapping (email and ticket generators will handle the rest via UI or utility functions)
    const newAction: OptimizationAction = {
      id: `ACT-${Math.floor(Math.random() * 10000)}`,
      recommendationId: rec.id,
      platform: rec.platform,
      resourceName: rec.resourceName,
      issue: rec.issue,
      owner: rec.owner,
      assignedTo: null,
      country: rec.country,
      businessUnit: rec.businessUnit,
      estimatedMonthlySavings: rec.monthlySavings,
      approvedMonthlySavings: null,
      estimatedAnnualSavings: rec.annualSavings,
      approvedAnnualSavings: null,
      riskLevel: rec.riskLevel,
      approvalRisk: rec.riskLevel === 'Low' ? 'Low' : 'Medium',
      status: 'New',
      dueDate: null,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      approvalNotes: [],
      actionPlan: rec.recommendedAction,
      generatedOwnerEmail: '', // Will be generated by util
      generatedTicketDraft: '', // Will be generated by util
    };
    setWorkflowActions(prev => [newAction, ...prev]);
  };

  const updateActionStatus = (actionId: string, status: WorkflowStatus, payload?: Partial<OptimizationAction>) => {
    setWorkflowActions(prev => prev.map(action => {
      if (action.id === actionId) {
        return {
          ...action,
          ...payload,
          status,
          updatedAt: new Date().toISOString(),
          ...(status === 'Completed' ? { completedAt: new Date().toISOString() } : {})
        };
      }
      return action;
    }));
  };

  const resetWorkflow = () => {
    setWorkflowActions([]);
    localStorage.removeItem('finops_workflow_actions');
  };

  return (
    <DataContext.Provider value={{
      sourceMode,
      setSourceMode,
      activeData,
      csvData,
      uploadCsvData,
      clearCsvData,
      dataFreshness,
      csvMetrics,
      workflowActions,
      createAction,
      updateActionStatus,
      resetWorkflow
    }}>
      {children}
    </DataContext.Provider>
  );
};

// eslint-disable-next-line react-refresh/only-export-components
export const useData = () => {
  const context = useContext(DataContext);
  if (context === undefined) {
    throw new Error('useData must be used within a DataProvider');
  }
  return context;
};
