export const config = {
  runtime: 'edge',
};

import { GoogleGenAI, Type, Schema } from '@google/genai';

const ai = new GoogleGenAI({
  apiKey: process.env.GEMINI_API_KEY || '',
});

const responseSchema: Schema = {
  type: Type.OBJECT,
  properties: {
    summary: {
      type: Type.STRING,
      description: "A 2-3 sentence executive summary of the response.",
    },
    estimatedSavings: {
      type: Type.NUMBER,
      description: "The numeric estimated monthly savings based purely on the provided context.",
    },
    riskCaveats: {
      type: Type.STRING,
      description: "Any risks, production impact warnings, or data quality caveats to consider.",
    },
    recommendedActions: {
      type: Type.ARRAY,
      items: { type: Type.STRING },
      description: "List of actionable steps the user should take. Clearly distinguish Quick Wins vs Change Required.",
    },
    ownerFollowUps: {
      type: Type.ARRAY,
      items: { type: Type.STRING },
      description: "List of actions required regarding resource owners (e.g. 'Contact IT for orphaned VMs').",
    },
    nextSteps: {
      type: Type.ARRAY,
      items: { type: Type.STRING },
      description: "Broader strategic next steps (e.g., 30/60/90 day plan items if requested).",
    },
    confidence: {
      type: Type.INTEGER,
      description: "A confidence score from 0 to 100 based on data quality.",
    },
    dataQualityNotes: {
      type: Type.STRING,
      description: "Notes on missing data or assumptions made.",
    }
  },
  required: ["summary", "recommendedActions", "confidence"],
};

export default async function handler(request: Request) {
  if (request.method !== 'POST') {
    return new Response(JSON.stringify({ error: 'Method not allowed' }), { status: 405 });
  }

  if (!process.env.GEMINI_API_KEY) {
    return new Response(JSON.stringify({ error: 'GEMINI_API_KEY is not configured on the server.' }), { status: 500 });
  }

  try {
    const body = await request.json();
    const { prompt, context, language = 'en' } = body;

    if (!prompt) {
      return new Response(JSON.stringify({ error: 'Missing user prompt.' }), { status: 400 });
    }

    const systemInstruction = `
You are an elite Hybrid FinOps advisor, Infrastructure optimization expert, and CIO-level analyst.
Your goal is to provide highly actionable, risk-aware recommendations to reduce cloud/hybrid waste.

Context provided by the Command Center Engine:
${JSON.stringify(context, null, 2)}

Strict Rules:
1. ONLY recommend actions based on the provided context. Do NOT invent platforms or resources not present.
2. NEVER recommend deleting Production workloads without explicit engineering validation.
3. ALWAYS distinguish between "Quick Wins" (zero downtime) and "Change Required" (downtime/risk).
4. Do not guess savings amounts. Use the numbers provided in the context.
5. Highlight any missing owners or data quality caveats.
6. Respond entirely in the user's requested language: ${language.toUpperCase()}.
`;

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: prompt,
      config: {
        systemInstruction,
        responseMimeType: 'application/json',
        responseSchema: responseSchema,
        temperature: 0.2, // Keep it deterministic and factual
      }
    });

    if (!response.text) {
      throw new Error("No response generated by Gemini.");
    }

    // Attempt to parse the JSON to ensure it's valid before sending to client
    const jsonResponse = JSON.parse(response.text);

    return new Response(JSON.stringify(jsonResponse), {
      status: 200,
      headers: { 'Content-Type': 'application/json' },
    });

  } catch (error: any) {
    console.error("Gemini Copilot Error:", error);
    return new Response(JSON.stringify({ error: 'Failed to generate Copilot response.', details: error.message }), { status: 500 });
  }
}
